version: "3"
services:
  client:
    container_name: client-cntnr
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    container_name: server-cntnr
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
# version: "3"
# services:
#   react-app:
#     image: react-app
#     stdin_open: true
#     ports:
#       - "3000:3000"
#     networks:
#       - mern-app
#   api-server:
#     image: api-server
#     ports:
#       - "5000:5000"
#     networks:
#       - mern-app
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo:3.6.19-xenial
#     ports:
#       - "27017:27017"
#     networks:
#       - mern-app
#     volumes:
#       - mongo-data:/data/db
# networks:
#   mern-app:
#     driver: bridge
# volumes:
#   mongo-data:
#     driver: local
