version: "3"
services:
  client:
    container_name: client-cntnr
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    container_name: server-cntnr
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
